Document: ascend
Title: Debian ascend Manual
Author: <insert document author here>
Abstract: This manual describes what ascend is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ascend/ascend.sgml.gz

Format: postscript
Files: /usr/share/doc/ascend/ascend.ps.gz

Format: text
Files: /usr/share/doc/ascend/ascend.text.gz

Format: HTML
Index: /usr/share/doc/ascend/html/index.html
Files: /usr/share/doc/ascend/html/*.html
